// app/layout.tsx

import './globals.css';
import Sidebar from '../components/Sidebar';
import React from 'react';
import Header from '@/components/Header';
import { Geist, Geist_Mono } from "next/font/google";
import { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import ReduxProvider from './Provider/ReduxProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ReduxProvider>
            <div className='flex h-screen'>
                <Sidebar/>
                <div className="flex-1 flex flex-col">
                  <Header />
                  {children}
              </div>
            </div>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
